apiVersion: v1
kind: Namespace
metadata:
  name: form
---

apiVersion: v1
kind: Service
metadata:
  name: go-tilti-example
  namespace: form
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-tilti-example
  type: ClusterIP
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: go-tilti-example
  namespace: form
data:
    APP_PROFILE: "dev"
---
